dataset_name: sprites
dataset_variant: sprites
data_type: 'Video'
classifier_loader_cfg:
  name: HuggingfaceLoader
  parameters:
    repo_id: "TalBarami/msd_judge_classifiers"
    repo_path: "${dataset_variant}_classifier_best.pth"
dataset:
  dataset:
    name: DisentanglementDataset
    parameters: { }
  reader:
    name: HuggingFaceReader
    parameters:
      repo_id: "TalBarami/msd_${dataset_variant}"
  preprocess_hooks:
    - name: ToNumpy
      parameters: {}
    - name: Transpose
      parameters:
        axes: [0, 3, 1, 2]
    - name: Normalize
      parameters:
        data_min: 0
        data_max: 255
  splits:
    train:
      preprocess_hooks: ${dataset.preprocess_hooks}
      loader:
        name: DataLoader
        parameters:
          batch_size: ${batch_size}
          shuffle: true
          pin_memory: true
          drop_last: true
    val:
      preprocess_hooks: ${dataset.preprocess_hooks}
      loader:
        name: DataLoader
        parameters:
          batch_size: ${test_batch_size}
          shuffle: false
          pin_memory: true
          drop_last: true
    test:
      preprocess_hooks: ${dataset.preprocess_hooks}
      loader:
        name: DataLoader
        parameters:
          batch_size: ${test_batch_size}
          shuffle: false
          pin_memory: true
          drop_last: true